version: '1'

services: 
  propertiesDB:
    image: postgres:15.3
    container_name: key-sphere
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data